on:
  push:
    branches:
      - 'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: NPM Install
        uses: actions/setup-node@v6
        with: 
          node-version: 24
      - run: npm ci
        
      - name: Install Ionic
        run: npm install -g ionic
        
      - name: Build with Ionic
        run: npm run ionic-build-prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website/
         
